excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://d0lfin.github.io
title: Awesome
email: to.dolfin@gmail.com
author: Alexey Emelin
description: My awesome new site
paginate: 3
google_analytics: 